language: ruby
rvm:
- 2.1.1
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: ISw3ke/gLOvLc8KMhxmQaWJzOqQuDWozovNl4Ko803WyVpUOkbi/N3tPABGKOcMJk6XJaCsDBYRHBQkgFhw+OHhsHIluf7+GZgVhIKz/WNlPCqdDAAcD/TtRpNM+QSCsDPh1FcvSNTAJLqtwdJX1HXnrmq2vNFtgw3BNzOfbAw4=
  app: g2-dashboard-staging
  on:
    repo: gSchool/g2-dashboard
  run:
    - "bundle exec rake db:migrate"
